=== mathi-naickan/opensaf/src/imm/SAI-AIS-IMM-XSD-A.02.13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp1 U (http://www.altova.com) by Maria Toeroe (Ericsson Canada/Open Systems Research) -->
<xs:schema xmlns:imm="http://www.saforum.org/IMMSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.saforum.org/IMMSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<!--
   OWNERSHIP OF SPECIFICATION AND COPYRIGHTS

   Copyright(c) 2009, Service Availability(TM) Forum. All rights reserved.

   Permission to use, copy, modify, and distribute this software for any
   purpose without fee is hereby granted, provided that this entire notice
   is included in all copies of any software which is or includes a copy
   or modification of this software and in all copies of the supporting
   documentation for such software.
  
   THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
   WARRANTY.  IN PARTICULAR, THE SERVICE AVAILABILITY FORUM DOES NOT MAKE ANY
   REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY
   OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.

  -->
	<!-- PART I - DEFINITION OF AN IMM OBJECT CLASS -->
	<!--
       Various types of IMM object attributes (SaImmValueTypeT)
    -->
	<xs:simpleType name="attr-value-type">
		<xs:annotation>
			<xs:documentation>Types of attribute's values</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="SA_INT32_T"/>
			<xs:enumeration value="SA_UINT32_T"/>
			<xs:enumeration value="SA_INT64_T"/>
			<xs:enumeration value="SA_UINT64_T"/>
			<xs:enumeration value="SA_NAME_T"/>
			<xs:enumeration value="SA_TIME_T"/>
			<xs:enumeration value="SA_FLOAT_T"/>
			<xs:enumeration value="SA_DOUBLE_T"/>
			<xs:enumeration value="SA_STRING_T"/>
			<xs:enumeration value="SA_ANY_T"/>
		</xs:restriction>
	</xs:simpleType>
	<!--
       Two categories of IMM classes & attributes)
    -->
	<xs:simpleType name="category">
		<xs:annotation>
			<xs:documentation>Class or attribute category</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="SA_CONFIG"/>
			<xs:enumeration value="SA_RUNTIME"/>
		</xs:restriction>
	</xs:simpleType>
	<!--
       Flags for object attributes (SaImmAttrFlagsT)
    -->
	<xs:simpleType name="attr-flags">
		<xs:annotation>
			<xs:documentation>Attribute flags</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="SA_MULTI_VALUE"/>
			<xs:enumeration value="SA_WRITABLE"/>
			<xs:enumeration value="SA_INITIALIZED"/>
			<xs:enumeration value="SA_PERSISTENT"/>
			<xs:enumeration value="SA_CACHED"/>
			<xs:enumeration value="SA_NO_DUPLICATES"/>
			<xs:enumeration value="SA_NOTIFY"/>
			<xs:enumeration value="SA_NO_DANGLING"/>
		</xs:restriction>
	</xs:simpleType>
	<!--
       Union of types for "value" and "default-value" elements
    -->
	<xs:simpleType name="value-type">
		<xs:annotation>
			<xs:documentation>Value type</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="xs:string xs:base64Binary"/>
	</xs:simpleType>
	<!-- 
      Group of XML elements common to RDN and other object attributes
    -->
	<xs:group name="attr-elements">
		<xs:annotation>
			<xs:documentation>Common elements to RDN and other attributes</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="type" type="imm:attr-value-type"/>
			<xs:element name="category" type="imm:category"/>
			<xs:element name="flag" type="imm:attr-flags" minOccurs="0" maxOccurs="5"/>
			<xs:element name="ntfid" type="xs:unsignedInt" default="0" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<!-- 
      Definition of an object's RDN attribute 
    -->
	<xs:complexType name="rdn-def">
		<xs:annotation>
			<xs:documentation>RDN attribute definition</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:group ref="imm:attr-elements"/>
		</xs:sequence>
	</xs:complexType>
	<!-- 
      Definition of an object's attribute (other than RDN)
      In addition to an RDN attribute, other attributes can be multi-value and can have a default value.
    -->
	<xs:complexType name="attr-def">
		<xs:annotation>
			<xs:documentation>Attribute definition</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:group ref="imm:attr-elements"/>
			<xs:element name="default-value" type="imm:value-type" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!-- 
      Definition of an object class
    -->
	<xs:complexType name="class-def">
		<xs:annotation>
			<xs:documentation>Object class definition</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="category" type="imm:category"/>
			<xs:element name="rdn" type="imm:rdn-def"/>
			<xs:element name="attr" type="imm:attr-def" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<!-- PART II - DEFINITION OF AN IMMS OBJECT INSTANCE -->
	<!-- 
      The object is defined by:
          - its object class
          - its DN (XML attribute)
          - all its attributes (name/values)
    -->
	<xs:complexType name="object-def">
		<xs:annotation>
			<xs:documentation>Object instance definition</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="dn" type="xs:string">
				<xs:annotation>
					<xs:documentation>Object Distinguished Name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attr" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Object's attributes</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="value" type="imm:value-type" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="class" type="xs:string"/>
	</xs:complexType>
	<!-- PART III- DEFINITION OF IMM Service CONTENTS-->
	<!-- 
        The IMM Service contents is defined as a list of class definitions followed by a list of objects
     -->
	<xs:element name="IMM-contents">
		<xs:annotation>
			<xs:documentation>IMM Service contents</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="class" type="imm:class-def" maxOccurs="unbounded"/>
				<xs:element name="object" type="imm:object-def" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mathi-naickan/opensaf/src/clm/clmsv_classes.xml
<?xml version="1.0" encoding="utf-8"?>
<imm:IMM-contents xmlns:imm="http://www.saforum.org/IMMSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SAI-AIS-IMM-XSD-A.02.13.xsd">
	<class name="SaClmNode">
                <category>SA_CONFIG</category>
                <rdn>
                        <name>safNode</name>
                        <type>SA_STRING_T</type>
                        <category>SA_CONFIG</category>
                        <flag>SA_INITIALIZED</flag>
                </rdn>
                <attr>
                        <name>saClmNodeDisableReboot</name>
                        <type>SA_UINT32_T</type>
                        <category>SA_CONFIG</category>
                        <flag>SA_WRITABLE</flag>
                        <default-value>0</default-value>
                </attr>
                <attr>
                        <name>saClmNodeEE</name>
                        <type>SA_NAME_T</type>
                        <category>SA_CONFIG</category>
                        <flag>SA_WRITABLE</flag>
                </attr>
                <attr>
                        <name>saClmNodeAddressFamily</name>
                        <type>SA_UINT32_T</type>
                        <category>SA_CONFIG</category>
                        <flag>SA_WRITABLE</flag>
                </attr>
                <attr>
                        <name>saClmNodeAddress</name>
                        <type>SA_STRING_T</type>
                        <category>SA_CONFIG</category>
                        <flag>SA_WRITABLE</flag>
                </attr>
		<attr>
                        <name>saClmNodeLockCallbackTimeout</name>
                        <type>SA_TIME_T</type>
                        <category>SA_CONFIG</category>
                        <flag>SA_WRITABLE</flag>
                </attr>
                <attr>
                        <name>saClmNodeID</name>
                        <type>SA_UINT32_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
                <attr>
                        <name>saClmNodeIsMember</name>
                        <type>SA_UINT32_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
                <attr>
                        <name>saClmNodeBootTimeStamp</name>
                        <type>SA_TIME_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
                <attr>
                        <name>saClmNodeInitialViewNumber</name>
                        <type>SA_UINT64_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
                <attr>
                        <name>saClmNodeCurrAddressFamily</name>
                        <type>SA_UINT32_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
                <attr>
                        <name>saClmNodeCurrAddress</name>
                        <type>SA_STRING_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
                <attr>
                        <name>saClmNodeAdminState</name>
                        <type>SA_UINT32_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_PERSISTENT</flag>
                        <flag>SA_CACHED</flag>
                        <default-value>1</default-value>
                </attr>
        </class>
	
	<class name="SaClmCluster">
                <category>SA_CONFIG</category>
                <rdn>
                        <name>safCluster</name>
                        <type>SA_STRING_T</type>
                        <category>SA_CONFIG</category>
                        <flag>SA_INITIALIZED</flag>
                </rdn>
                <attr>
                        <name>saClmClusterNumNodes</name>
                        <type>SA_UINT32_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
                <attr>
                        <name>saClmClusterInitTimestamp</name>
                        <type>SA_TIME_T</type>
                        <category>SA_RUNTIME</category>
                        <flag>SA_CACHED</flag>
                </attr>
        </class>

</imm:IMM-contents>

=== mathi-naickan/opensaf/src/ckpt/cpsv_classes.xml
<?xml version="1.0" encoding="utf-8"?>
<imm:IMM-contents xmlns:imm="http://www.saforum.org/IMMSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SAI-AIS-IMM-XSD-A.02.13.xsd">
	<class name="SaCkptCheckpoint">
		<category>SA_RUNTIME</category>
		<rdn>
			<name>safCkpt</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</rdn>
		<attr>
			<name>saCkptCheckpointCreationTimestamp</name>
			<type>SA_TIME_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saCkptCheckpointSize</name>
			<type>SA_UINT64_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointUsedSize</name>
			<type>SA_UINT64_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointCreationFlags</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saCkptCheckpointRetDuration</name>
			<type>SA_TIME_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointMaxSections</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saCkptCheckpointMaxSectionSize</name>
			<type>SA_UINT64_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saCkptCheckpointMaxSectionIdSize</name>
			<type>SA_UINT64_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saCkptCheckpointNumOpeners</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointNumReaders</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointNumWriters</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointNumReplicas</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointNumSections</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>saCkptCheckpointNumCorruptSections</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
	</class>
	<class name="SaCkptReplica">
		<category>SA_RUNTIME</category>
		<rdn>
			<name>safReplica</name>
			<type>SA_NAME_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</rdn>
		<attr>
			<name>saCkptReplicaIsActive</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
	</class>
</imm:IMM-contents>

=== mathi-naickan/opensaf/src/msg/mqsv_sc_template.xml
<?xml version="1.0" encoding="utf-8"?>
<imm:IMM-contents xmlns:imm="http://www.saforum.org/IMMSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SAI-AIS-IMM-XSD-A.02.13.xsd">
	<object class="SaAmfComp">
		<dn>safComp=MQD,safSu=SC_2_1,safSg=2N,safApp=OpenSAF</dn>
		<attr>
			<name>saAmfCompType</name>
			<value>safVersion=4.0.0,safCompType=OpenSafCompTypeMQD</value>
		</attr>
	</object>
	<object class="SaAmfCompCsType">
		<dn>safSupportedCsType=safVersion=4.0.0\,safCSType=MQD-OpenSAF,safComp=MQD,safSu=SC_2_1,safSg=2N,safApp=OpenSAF</dn>
	</object>
	<object class="SaAmfComp">
		<dn>safComp=MQND,safSu=SC_2_1,safSg=NoRed,safApp=OpenSAF</dn>
		<attr>
			<name>saAmfCompType</name>
			<value>safVersion=4.0.0,safCompType=OpenSafCompTypeMQND</value>
		</attr>
	</object>
	<object class="SaAmfCSI">
		<dn>safCsi=MQND,safSi=NoRed_TOKEN,safApp=OpenSAF</dn>
		<attr>
			<name>saAmfCSType</name>
			<value>safVersion=4.0.0,safCSType=MQND-OpenSAF</value>
		</attr>
	</object>
	<object class="SaAmfCompCsType">
		<dn>safSupportedCsType=safVersion=4.0.0\,safCSType=MQND-OpenSAF,safComp=MQND,safSu=SC_2_1,safSg=NoRed,safApp=OpenSAF</dn>
	</object>
</imm:IMM-contents>

=== mathi-naickan/opensaf/src/clm/clmsv_plm_sc_template.xml
<?xml version="1.0" encoding="utf-8"?>
<imm:IMM-contents xmlns:imm="http://www.saforum.org/IMMSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SAI-AIS-IMM-XSD-A.02.13.xsd">
	<object class="SaAmfComp">
		<dn>safComp=CLM,safSu=SC_2_1,safSg=2N,safApp=OpenSAF</dn>
		<attr>
			<name>saAmfCompType</name>
			<value>safVersion=4.0.0,safCompType=OpenSafCompTypeCLM</value>
		</attr>
	</object>
	<object class="SaAmfCompCsType">
		<dn>safSupportedCsType=safVersion=4.0.0\,safCSType=CLM-OpenSAF,safComp=CLM,safSu=SC_2_1,safSg=2N,safApp=OpenSAF</dn>
	</object>
	<object class="SaAmfComp">
		<dn>safComp=CLMNA,safSu=SC_2_1,safSg=NoRed,safApp=OpenSAF</dn>
		<attr>
			<name>saAmfCompType</name>
			<value>safVersion=4.0.0,safCompType=OpenSafCompTypeCLMNA</value>
		</attr>
	</object>
	<object class="SaAmfCSI">
		<dn>safCsi=CLMNA,safSi=NoRed_TOKEN,safApp=OpenSAF</dn>
		<attr>
			<name>saAmfCSType</name>
			<value>safVersion=4.0.0,safCSType=CLMNA-OpenSAF</value>
		</attr>
	</object>
	<object class="SaAmfCompCsType">
		<dn>safSupportedCsType=safVersion=4.0.0\,safCSType=CLMNA-OpenSAF,safComp=CLMNA,safSu=SC_2_1,safSg=NoRed,safApp=OpenSAF</dn>
	</object>
	<object class="SaClmNode">
                <dn>safNode=CLM_TOKEN,safCluster=myClmCluster</dn>
<!-- By default, no SaClmNode is mapped to SaPlmEE. If this mapping is needed then uncomment the following lines -->
<!--                <attr>
                        <name>saClmNodeEE</name>
                        <value>safEE=SC_2_1,safDomain=domain_1</value>
                </attr>
-->
                <attr>
                        <name>saClmNodeLockCallbackTimeout</name>
                        <value>50000000000</value>
                </attr>

        </object>
</imm:IMM-contents>

=== mathi-naickan/opensaf/src/evt/edsv_sc_template.xml
<?xml version="1.0" encoding="utf-8"?>
<imm:IMM-contents xmlns:imm="http://www.saforum.org/IMMSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SAI-AIS-IMM-XSD-A.02.13.xsd">
	<object class="SaAmfComp">
		<dn>safComp=EDS,safSu=SC_2_1,safSg=2N,safApp=OpenSAF</dn>
		<attr>
			<name>saAmfCompType</name>
			<value>safVersion=4.0.0,safCompType=OpenSafCompTypeEDS</value>
		</attr>
	</object>
	<object class="SaAmfCompCsType">
		<dn>safSupportedCsType=safVersion=4.0.0\,safCSType=EDS-OpenSAF,safComp=EDS,safSu=SC_2_1,safSg=2N,safApp=OpenSAF</dn>
	</object>
</imm:IMM-contents>

=== mathi-naickan/opensaf/src/log/logsv_classes.xml
<?xml version="1.0" encoding="utf-8"?>
<imm:IMM-contents xmlns:imm="http://www.saforum.org/IMMSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SAI-AIS-IMM-XSD-A.02.13.xsd">
	<class name="SaLogStream">
		<category>SA_RUNTIME</category>
		<rdn>
			<name>safLgStr</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</rdn>
		<attr>
			<name>saLogStreamFileName</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamPathName</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamMaxLogFileSize</name>
			<type>SA_UINT64_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamFixedLogRecordSize</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamHaProperty</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
			</attr>
		<attr>
			<name>saLogStreamLogFullAction</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamMaxFilesRotated</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamLogFileFormat</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamSeverityFilter</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamCreationTimestamp</name>
			<type>SA_TIME_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamNumOpeners</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logStreamDiscardedCounter</name>
			<type>SA_UINT64_T</type>
			<category>SA_RUNTIME</category>
		</attr>
	</class>
	<class name="SaLogStreamConfig">
		<category>SA_CONFIG</category>
		<rdn>
			<name>safLgStrCfg</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_INITIALIZED</flag>
		</rdn>
		<attr>
			<name>saLogStreamFileName</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_INITIALIZED</flag>
			<flag>SA_WRITABLE</flag>
		</attr>
		<attr>
			<name>saLogStreamPathName</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_INITIALIZED</flag>
		</attr>
		<attr>
			<name>saLogStreamMaxLogFileSize</name>
			<type>SA_UINT64_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
			<default-value>5000000</default-value>
		</attr>
		<attr>
			<name>saLogStreamFixedLogRecordSize</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
			<default-value>150</default-value>
		</attr>
		<attr>
			<name>saLogStreamLogFullAction</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
			<default-value>3</default-value>
		</attr>
		<attr>
			<name>saLogStreamLogFullHaltThreshold</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
			<default-value>75</default-value>
		</attr>
		<attr>
			<name>saLogStreamMaxFilesRotated</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
			<default-value>4</default-value>
		</attr>
		<attr>
			<name>saLogStreamLogFileFormat</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
		</attr>
		<attr>
			<name>saLogStreamSeverityFilter</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
		</attr>
		<attr>
			<name>saLogStreamCreationTimestamp</name>
			<type>SA_TIME_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</attr>
		<attr>
			<name>saLogStreamNumOpeners</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logStreamDiscardedCounter</name>
			<type>SA_UINT64_T</type>
			<category>SA_RUNTIME</category>
		</attr>
	</class>
	<class name="OpenSafLogConfig">
<!-- Care is needed when changing to the default values for the attributes of this class
to ensure that default global values in the implementation are also changed accordingly.
--> 
		<category>SA_CONFIG</category>
		<rdn>
			<name>logConfig</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_INITIALIZED</flag>
		</rdn>
		<attr>
			<name>logRootDirectory</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_INITIALIZED</flag>
			<flag>SA_WRITABLE</flag>
		</attr>
		<attr>
			<name>logMaxLogrecsize</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
            <default-value>1024</default-value>
		</attr>
		<attr>
			<name>logStreamFileFormat</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
		</attr>
		<attr>
			<name>logStreamSystemHighLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
            <default-value>0</default-value>
		</attr>
		<attr>
			<name>logStreamSystemLowLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
            <default-value>0</default-value>
		</attr>
		<attr>
			<name>logStreamAppHighLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
            <default-value>0</default-value>
		</attr>
		<attr>
			<name>logStreamAppLowLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
            <default-value>0</default-value>
		</attr>
		<attr>
			<name>logMaxApplicationStreams</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
            <default-value>64</default-value>
		</attr>
		<attr>
			<name>logFileIoTimeout</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
            <default-value>500</default-value>
		</attr>
		<attr>
			<name>logFileSysConfig</name>
			<type>SA_UINT32_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
			<default-value>1</default-value>
		</attr>
		<attr>
			<name>logDataGroupname</name>
			<type>SA_STRING_T</type>
			<category>SA_CONFIG</category>
			<flag>SA_WRITABLE</flag>
		</attr>
	</class>
	<class name="OpenSafLogCurrentConfig">
		<category>SA_RUNTIME</category>
		<rdn>
			<name>logConfig</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
			<flag>SA_CACHED</flag>
		</rdn>
		<attr>
			<name>logRootDirectory</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logMaxLogrecsize</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logStreamFileFormat</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logStreamSystemHighLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logStreamSystemLowLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logStreamAppHighLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logStreamAppLowLimit</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logMaxApplicationStreams</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logFileIoTimeout</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logFileSysConfig</name>
			<type>SA_UINT32_T</type>
			<category>SA_RUNTIME</category>
		</attr>
		<attr>
			<name>logDataGroupname</name>
			<type>SA_STRING_T</type>
			<category>SA_RUNTIME</category>
		</attr>
	</class>
</imm:IMM-contents>
